#!/bin/bash
#
# Write a command file with one step per month of ERA5 2 m temperature.
#
# Each step runs ./run_step.sh, which runs climatology.py with 16 threads over
# one month (744 x 721 x 1440 float32, about 3 GB for a 31-day month).  With
# --nthreads 16 --steps-per-node 8, launch_cf puts 8 steps on each node, one
# per NUMA domain's worth of cores.
#
# Passing "pin" prefixes every step with
#
#     numactl --cpunodebind=<d> --membind=<d>
#
# which keeps the step's threads and its memory in NUMA domain d.  launch_cf
# hands out steps to nodes in blocks of 8, so d simply cycles 0-7 down the file
# (see ../gen_cmdfile_numactl.sh).  A domain has about 30 GB of memory, so a
# bound step's 3 GB fits easily.
#
# Unpinned, a step's memory lands in whichever domain its main thread is on
# when it reads the file, and its threads go wherever the scheduler puts them.
# numa_test.sh found that costs a full node about 40% of its throughput.
#
# Generate both files, submit both, and compare the runs with ./compare_runs.sh.
#
# Usage:  ./gen_cmdfile_numa.sh             unpinned, writes ./cmdfile
#         ./gen_cmdfile_numa.sh pin         pinned,   writes ./cmdfile.pinned
#         ./gen_cmdfile_numa.sh pin <file>  pinned,   writes <file>
#
#         START=201501 NSTEPS=48 ./gen_cmdfile_numa.sh
#           48 months from January 2015 (default: 24 from January 2019)
#
#         SRCDIR=/some/dir ./gen_cmdfile_numa.sh
#           files laid out as on GDEX, <SRCDIR>/<YYYYMM>/<product>.<param>.*.nc

#------------------------------------------------------------------
start="${START:-201901}"     # first month, YYYYMM
nsteps="${NSTEPS:-24}"       # months == steps; a multiple of 8 fills every node
steps_per_node=8             # NUMA domains per node
threads=16                   # cores per NUMA domain
product="e5.oper.an.sfc"
param="128_167_2t"           # 2 m temperature
#------------------------------------------------------------------

# "pin" is a keyword wherever it appears; any other argument is the output file
pin=""
output=""
for arg in "$@"; do
    if [ "${arg}" = "pin" ]; then
        pin="yes"
    elif [ -z "${output}" ]; then
        output="${arg}"
    else
        echo "ERROR: unexpected argument '${arg}'"
        echo "usage: ./gen_cmdfile_numa.sh [pin] [output file]"
        exit 1
    fi
done
if [ -n "${pin}" ]; then
    output="${output:-./cmdfile.pinned}"
else
    output="${output:-./cmdfile}"
fi

# run_step.sh's barrier waits for 8 steps on every node, so a partly filled
# last node would wait out its timeout (10 minutes) before computing
if [ $(( nsteps % steps_per_node )) -ne 0 ]; then
    echo "ERROR: NSTEPS=${nsteps} is not a multiple of ${steps_per_node}; the last node would"
    echo "       run fewer steps than run_step.sh waits for."
    exit 1
fi

srcdir="${SRCDIR:-}"
if [ -z "${srcdir}" ]; then
    for root in /glade/campaign/collections/gdex/data /gdex/data \
                /glade/campaign/collections/rda/data; do
        if [ -d "${root}/d633000/${product}" ]; then
            srcdir="${root}/d633000/${product}"
            break
        fi
    done
fi
[ -d "${srcdir}" ] || { echo "ERROR: cannot find d633000/${product} on GLADE -- set SRCDIR"; exit 1; }

# one file per month, in order
files=()
y=${start:0:4}
m=$(( 10#${start:4:2} ))
for (( i = 0; i < nsteps; i++ )); do
    ym=$(printf "%04d%02d" "${y}" "${m}")
    f=$(ls "${srcdir}/${ym}/${product}.${param}".*.nc 2>/dev/null | head -1)
    [ -n "${f}" ] || { echo "ERROR: no ${param} file for ${ym} in ${srcdir}/${ym}"; exit 1; }
    files+=("${f}")
    (( m++ )); [ ${m} -gt 12 ] && { m=1; (( y++ )); }
done

{
    echo "# ${nsteps} steps, one month of ERA5 ${param} each, ${files[0]##*/} onwards"
    if [ -n "${pin}" ]; then
        echo "# Each step is bound to one NUMA domain, threads and memory, with numactl."
    else
        echo "# Steps are not bound; the Linux scheduler places them."
    fi
    echo "#"
    echo "# Submit with:"
    echo "#   launch_cf -A \$PBS_ACCOUNT -l walltime=00:20:00 \\"
    echo "#             --nthreads ${threads} --steps-per-node ${steps_per_node} ${output}"
    echo "#"
    echo "# Generated by gen_cmdfile_numa.sh"

    for (( i = 0; i < nsteps; i++ )); do
        if [ -n "${pin}" ]; then
            # steps 0..7 go to domains 0..7, then the numbering starts over
            d=$(( i % steps_per_node ))
            echo "numactl --cpunodebind=${d} --membind=${d} ./run_step.sh pinned ${files[i]}"
        else
            echo "./run_step.sh unpinned ${files[i]}"
        fi
    done
} > "${output}"

echo "Wrote ${nsteps} steps to ${output}"
echo " -> ${steps_per_node} steps/node, ${threads} threads/step, $(( nsteps / steps_per_node )) nodes"
if [ -n "${pin}" ]; then
    echo " -> each step bound to one NUMA domain with numactl"
else
    echo " -> steps unbound, placed by the Linux scheduler"
fi
