#!/bin/bash
#
# Write a command file whose steps are PINNED, one step per NUMA domain.
#
# A Derecho compute node has 128 cores arranged as 8 NUMA domains of 16 cores:
#
#     domain 0 -> cores   0- 15        domain 4 -> cores  64- 79
#     domain 1 -> cores  16- 31        domain 5 -> cores  80- 95
#     domain 2 -> cores  32- 47        domain 6 -> cores  96-111
#     domain 3 -> cores  48- 63        domain 7 -> cores 112-127
#
# Memory is attached to domains too, so a thread running in domain 3 reads its
# own domain's memory quickly and another domain's memory slowly.
#
# With 8 steps per node and 16 threads per step, one step fits one domain
# exactly.  Prefixing a step with
#
#     numactl --cpunodebind=3 --membind=3
#
# keeps that step's 16 threads inside domain 3 (--cpunodebind) and makes them
# allocate their memory there (--membind).  Without the prefix the Linux
# scheduler is free to spread one step's threads over all 8 domains, so most
# of its memory traffic becomes remote.
#
# launch_cf hands out steps to nodes in blocks of "steps per node", so the
# domain number simply cycles 0,1,...,7,0,1,... down the command file.
#
# numactl picks the domain, but it does not say which core inside that domain
# each thread runs on -- the scheduler can still put two threads of a step on one
# core and leave another idle.  Passing "bind" as the second argument also emits
#
#     OMP_PROC_BIND=close OMP_PLACES=cores
#
# in front of each step, which gives every thread its own physical core.
#
# Usage:  ./gen_cmdfile_numactl.sh [output file] [bind]
#           default output: ./cmdfile.numactl

#------------------------------------------------------------------
# edit these four values to match the job you intend to submit
nsteps=16                    # total steps == lines in the command file
domains=8                    # NUMA domains per node == steps per node
threads=16                   # threads per step == cores per NUMA domain
exe="../hello_omp.exe"       # the program each step runs
#------------------------------------------------------------------

output="${1:-./cmdfile.numactl}"

# with "bind", each step also gets one thread per physical core in its domain
prefix=""
[ "${2}" = "bind" ] && prefix="OMP_PROC_BIND=close OMP_PLACES=cores "

{
    echo "# ${nsteps} steps, pinned one per NUMA domain."
    if [ -n "${prefix}" ]; then
        echo "# Each step also binds one thread per physical core."
    fi
    echo "#"
    echo "# Submit with:"
    echo "#   launch_cf -A \$PBS_ACCOUNT -l walltime=00:10:00 \\"
    echo "#             --nthreads ${threads} --steps-per-node ${domains} ${output}"
    echo "#"
    echo "# Generated by gen_cmdfile_numactl.sh"

    for step in $(seq 1 ${nsteps}); do
        # steps 1..8 go to domains 0..7, then the numbering starts over
        domain=$(( (step - 1) % domains ))
        echo "${prefix}numactl --cpunodebind=${domain} --membind=${domain} ${exe} ${step}"
    done
} > "${output}"

echo "Wrote ${nsteps} pinned steps to ${output}"
echo " -> ${domains} steps/node, ${threads} threads/step, one NUMA domain each"
if [ -n "${prefix}" ]; then
    echo " -> plus OMP_PROC_BIND=close OMP_PLACES=cores, one thread per core"
fi
