#!/bin/bash
#
# Write a command file with one step per input NetCDF file.
#
# Each step runs ./process_file.sh, which runs several NCO operations over its
# file at the same time (see the comments there).
#
# Passing "pin" as the second argument prefixes every step with
#
#     taskset -c <core>
#
# which locks that step -- and therefore all of its concurrent ncks processes --
# onto a single core.  Generate both files, submit both, and compare how long
# the array took.  launch_cf hands out steps to nodes in blocks of "steps per
# node", so the core number simply cycles 0,1,...,127,0,1,... down the file.
#
# Usage:  ./gen_cmdfile_postproc.sh [output file] [pin]
#           default output: ./cmdfile

#------------------------------------------------------------------
datadir="./data"             # where make_data.sh put the input files
cores_per_node=128           # steps per node == cores per Derecho node
outdir="./out"               # where each step writes its per-variable files
#------------------------------------------------------------------

output="${1:-./cmdfile}"

# with "pin", each step is confined to one core
pin=""
if [ "${2:-}" = "pin" ]; then
    pin="yes"
fi

files=( ${datadir}/*.nc )
if [ ${#files[@]} -eq 0 ] || [ ! -r "${files[0]}" ]; then
    echo "ERROR: no input files in ${datadir}/ -- run ./make_data.sh first"
    exit 1
fi

{
    echo "# ${#files[@]} steps, one per NetCDF file in ${datadir}/"
    if [ -n "${pin}" ]; then
        echo "# Each step is pinned to a single core with taskset."
    else
        echo "# Steps are not pinned; the Linux scheduler places them."
    fi
    echo "#"
    echo "# Submit with:"
    echo "#   launch_cf -A \$PBS_ACCOUNT -l walltime=00:20:00 ${output}"
    echo "#"
    echo "# Generated by gen_cmdfile_postproc.sh"

    step=0
    for f in "${files[@]}"; do
        if [ -n "${pin}" ]; then
            echo "taskset -c $(( step % cores_per_node )) ./process_file.sh ${f} ${outdir}"
        else
            echo "./process_file.sh ${f} ${outdir}"
        fi
        step=$(( step + 1 ))
    done
} > "${output}"

echo "Wrote ${#files[@]} steps to ${output}"
if [ -n "${pin}" ]; then
    echo " -> each step pinned to one core with taskset"
else
    echo " -> steps unpinned, placed by the Linux scheduler"
fi
